# This workflow is triggered when a GitHub release is created.
# It can also be run manually to re-publish to NPM in case it failed for some reason.
# You can run this workflow by navigating to https://www.github.com/hdemirev/hari-public-repo/actions/workflows/publish-npm.yml
name: Publish NPM
on:
  workflow_dispatch:

  release:
    types: [published]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          yarn install

      - name: Publish to NPM
        run: |
          bash ./bin/publish-npm
        env:
          NPM_TOKEN: ${{ secrets.HARI_NEW_TEST_ORG_PROJECT_2_NPM_TOKEN || secrets.NPM_TOKEN }}
